title: 연습용 깃헙 페이지
email: wngks8321@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  연습용으로 만들어진 깃헙 페이지 입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wngks8321.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username: wngks8321

# Build settings
theme: minima
plugins:
  - jekyll-feed

tipue_search:
  include:
    pages: false
    collections: []
  exclude:
    files: [search.html, index.html, tags.html]
    categories: []
    tags: []